# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    # Package(-lock).json files stored in repository root
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "npm"
    # ignore:
    #   - dependency-name: "fill-pot-po"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github actions"
