name: Lint | Test

on:
  workflow_dispatch:

  pull_request:
    # types: [opened, reopened, synchronize] # Default
    # types: [opened, reopened, synchronize, edited, unlocked]
    # branches:
    #   - main
    # Only run when push includes commits with changes to:
    paths:
      # - 'src/**.js'
      - 'index.js'
      - 'test/**.js'
      - 'test/**.pot?'
      - 'jest.config.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run ESlint
        run: npm run lint

  test:
    name: Test (Node ${{ matrix.node-version }} on ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        node-version:
          # - 12.x
          # - 14.x
          - 16.x
        os:
          - ubuntu-latest
          - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run Jest
        run: npm test
