name: Combine PRs

# Controls when the action will run - in this case triggered manually
on:
  workflow_dispatch:
    inputs:
      branchPrefix:
        description: 'Branch prefix to find combinable PRs based on'
        type: string
        required: true
        default: 'dependabot'
      statusesFilter:
        description: 'Only combine PRs with statuses with these states (comma-separated)'
        type: string
        required: true
        default: 'success'
      checkRunsFilter:
        description: 'Only combine PRs with check-runs with these conclusions (comma-separated)'
        type: string
        required: true
        default: 'neutral,success,skipped'
      combineBranchName:
        description: 'Name of the branch to combine PRs into'
        type: string
        required: true
        default: 'combine-prs-branch'
      ignoreLabels:
        description: 'Exclude PRs with these labels (comma-separated)'
        type: string
        required: true
        default: 'nocombine'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "combine-prs"
  combine-prs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/github-script@v6
        id: fetch-branch-names
        name: Fetch branch names
        # env:
        #   BRANCH_PREFIX: ${{ inputs.branchPrefix }}
        #   STATUSES_FILTER: ${{ inputs.statusesFilter }}
        #   CHECKRUN_FILTER: ${{ inputs.checkRunsFilter }}
        #   IGNORE_LABELS: ${{ inputs.ignoreLabels }}
        with:
          # github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            const branchPrefix = context.payload.inputs.branchPrefix;
            const statusesFilter = context.payload.inputs.statusesFilter;
            const checkRunsFilter = context.payload.inputs.checkRunsFilter;
            const ignoreLabels = context.payload.inputs.ignoreLabels;

            // all: 'success,pending,failure,error'
            // default: 'success'
            const included_statuses = statusesFilter.split(',')
              .map( v => v.trim() )
              .filter( v => v.length > 0 );

            // all: 'action_required,cancelled,failure,neutral,success,skipped,stale,timed_out'
            // default: 'neutral,success,skipped'
            const included_checkruns = checkRunsFilter.split(',')
              .map( v => v.trim() )
              .filter( v => v.length > 0 );

            // default: 'nocombine'
            const ignore_labels = ignoreLabels.split(',')
              .map( v => v.trim() )
              .filter( v => v.length > 0 );

            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const base_branch = context.payload.ref.replace(/^refs\/heads\//, '');
            let branches = [];
            let prs = [];

            const pulls = await github.paginate(
              'GET /repos/{owner}/{repo}/pulls',
              { owner, repo, base: base_branch }
            );
            if ( pulls.length === 0 ) {
              core.setFailed('No PRs/branches found');
              return;
            }
            console.log('Found ' + pulls.length + ' pull request' + (pulls.length === 1 ? '': 's') );

            for ( const pull of pulls ) {
              // pull.head.ref = 'dependabot/etc/etc'
              // pull.number = 1
              // pull.state = 'open'
              // pull.locked = false
              // pull.draft = false
              // pull.base.ref = 'main'
              // pull.title
              // pull.labels[] = { name: '', color: 'ffffff', description: '' }
              // pull._links.html.href // url to GitHub PR page
              const branch = pull.head.ref;
              const matched_branch = branch.startsWith( branchPrefix );

              if ( ! matched_branch ) {
                console.log('PR #' + pull.number + ' (skip)' + ' - ' + branch );
              } else {
                statusOK = true;

                core.startGroup('PR #' + pull.number + ' - ' + branch );

                console.log('Checking statuses:');
                const combined_status = await github.paginate(
                  'GET /repos/{owner}/{repo}/commits/{ref}/status',
                  { owner, repo,
                    ref: branch
                  }
                );
                if ( combined_status.length > 0 && combined_status[0].statuses.length > 0 ) {
                  const statuses_ok = combined_status[0].statuses
                    .reduce( ( check, status ) => {
                      return check && included_statuses.includes( status.state );
                    }, true );
                  if ( ! statuses_ok ) {
                    console.log('FAIL: Invalid state of one or more statuses.');
                    statusOK = false;
                  } else {
                    console.log('PASS');
                  }
                }

                if ( statusOK ) {
                  console.log('');
                  console.log('Checking check-runs:');
                  const checkruns = await github.paginate(
                    'GET /repos/{owner}/{repo}/commits/{ref}/check-runs',
                    { owner, repo,
                      ref: branch
                    }
                  );
                  if ( checkruns.length > 0 ) {
                    const checkruns_ok = checkruns
                      .reduce( ( check, checkrun ) => {
                        return ( check
                          && 'completed' === checkrun.status
                          && included_checkruns.includes( checkrun.conclusion )
                        );
                      }, true );
                    if ( ! checkruns_ok ) {
                      console.log('FAIL: Invalid status or conclusion of one or more check-runs.');
                      statusOK = false;
                    } else {
                      console.log('PASS');
                    }
                  }
                }

                if ( statusOK ) {
                  console.log('');
                  console.log('Checking ignore labels:');
                  const labels = pull.labels;
                  if ( labels.length > 0 ) {
                    const labels_force_skip = labels
                      .reduce( ( check, label ) => {
                        return ( check || ignore_labels.includes( label.name ) );
                      }, false );
                    if ( labels_force_skip ) {
                      console.log('MATCH: One or more labels matched.');
                      statusOK = false;
                    } else {
                      console.log('NO MATCH');
                    }
                  } else {
                    console.log('NONE');
                  }
                }

                console.log('');
                if ( statusOK ) {
                  console.log('Result: INCLUDE');
                  branches.push( branch );
                  prs.push('* #' + pull.number );
                  // prs.push('* #' + pull.number + ' ' + pull.title );
                } else {
                  console.log('Result: SKIP');
                }

                core.endGroup();
              }
            }

            if ( branches.length == 0 ) {
              core.setFailed('No PRs/branches matched criteria');
              return;
            }
            console.log('Combined:');
            console.log( '- ' + branches.join('\n- ') );

            core.setOutput('base-branch', base_branch );
            core.setOutput('prs-string', prs.join('\n') );
            return branches.join(' ');

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Creates a branch with other PR branches merged together
      - name: Created combined branch
        env:
          BASE_BRANCH: ${{ steps.fetch-branch-names.outputs.base-branch }}
          BRANCHES_TO_COMBINE: ${{ steps.fetch-branch-names.outputs.result }}
          COMBINE_BRANCH_NAME: ${{ inputs.combineBranchName }}
        run: |
          echo "$BRANCHES_TO_COMBINE"
          sourcebranches="${BRANCHES_TO_COMBINE%\"}"
          sourcebranches="${sourcebranches#\"}"
          
          basebranch="${BASE_BRANCH%\"}"
          basebranch="${basebranch#\"}"
          
          git config pull.rebase false
          git config --global user.name 'vHeemstra'
          git config --global user.email '17368112+vHeemstra@users.noreply.github.com'
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          
          git branch $COMBINE_BRANCH_NAME $basebranch
          git checkout $COMBINE_BRANCH_NAME
          git pull origin $sourcebranches --no-edit
          git push origin $COMBINE_BRANCH_NAME

      # Creates a PR with the new combined branch
      - uses: actions/github-script@v6
        name: Create Combined Pull Request
        env:
          PRS_STRING: ${{ steps.fetch-branch-names.outputs.prs-string }}
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          script: |
            const repo = context.repo.repo;
            const owner = context.repo.owner;

            const prString = process.env.PRS_STRING;
            const body = 'This PR was created by the Combine PRs action by combining the following PRs:\n' + prString;
            // const response = await github.rest.pulls.create( { owner, repo,
            const response = await github.request(
              'POST /repos/{owner}/{repo}/pulls',
              { owner, repo,
                title: 'Combined PR',
                head: '${{ inputs.combineBranchName }}',
                base: '${{ steps.fetch-branch-names.outputs.base-branch }}',
                body: body
              }
            );
            console.log( response );

            await github.rest.issues.addLabels( {
              owner, repo,
              issue_number: response.data.number,
              labels: ['dependencies', 'npm']
            } );
